CREATE TABLE `ext_keyword_daily_stats` (
  `id` int AUTO_INCREMENT NOT NULL,
  `user_id` int NOT NULL,
  `query` varchar(255) NOT NULL,
  `stat_date` varchar(10) NOT NULL,
  `snapshot_count` int DEFAULT 0,
  `product_count` int DEFAULT 0,
  `avg_price` int DEFAULT 0,
  `avg_rating` decimal(3,1) DEFAULT '0',
  `avg_review` int DEFAULT 0,
  `total_review_sum` int DEFAULT 0,
  `ad_count` int DEFAULT 0,
  `ad_ratio` int DEFAULT 0,
  `rocket_count` int DEFAULT 0,
  `high_review_count` int DEFAULT 0,
  `competition_score` int DEFAULT 0,
  `competition_level` enum('easy','medium','hard') DEFAULT 'medium',
  `review_growth` int DEFAULT 0,
  `sales_estimate` int DEFAULT 0,
  `price_change` int DEFAULT 0,
  `product_count_change` int DEFAULT 0,
  `demand_score` int DEFAULT 0,
  `keyword_score` int DEFAULT 0,
  `created_at` timestamp DEFAULT (now()) NOT NULL,
  `updated_at` timestamp DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT `ext_keyword_daily_stats_id` PRIMARY KEY(`id`),
  UNIQUE KEY `uq_user_query_date` (`user_id`, `query`, `stat_date`),
  KEY `idx_user_date` (`user_id`, `stat_date`),
  KEY `idx_user_query` (`user_id`, `query`)
);
