-- AI 제품 발견 시스템 테이블

CREATE TABLE IF NOT EXISTS `ext_discovery_jobs` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `user_id` int NOT NULL,
  `keyword` varchar(255) NOT NULL,
  `status` enum('pending','crawling_search','filtering','crawling_detail','analyzing','completed','failed') NOT NULL DEFAULT 'pending',
  `max_pages` int DEFAULT 2,
  `max_detail_products` int DEFAULT 8,
  `search_results_json` json,
  `search_summary_json` json,
  `filtered_product_ids` json,
  `filter_criteria` json,
  `detail_results_json` json,
  `detail_crawled_count` int DEFAULT 0,
  `ai_analysis_json` json,
  `error_message` text,
  `started_at` timestamp NULL,
  `completed_at` timestamp NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `idx_discovery_jobs_user_status` (`user_id`, `status`),
  INDEX `idx_discovery_jobs_keyword` (`user_id`, `keyword`)
);

CREATE TABLE IF NOT EXISTS `ext_discovery_products` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `user_id` int NOT NULL,
  `job_id` int NOT NULL,
  `keyword` varchar(255) NOT NULL,
  `coupang_product_id` varchar(50) NOT NULL,
  `product_title` varchar(1000) NOT NULL,
  `product_url` text,
  `image_url` text,
  `price` int DEFAULT 0,
  `original_price` int DEFAULT 0,
  `rating` decimal(3,1) DEFAULT 0,
  `review_count` int DEFAULT 0,
  `seller_name` varchar(255),
  `delivery_type` varchar(50),
  `category_path` varchar(500),
  `option_count` int DEFAULT 0,
  `detail_data_json` json,
  `search_rank` int DEFAULT 0,
  `is_ad` boolean DEFAULT false,
  `is_rocket` boolean DEFAULT false,
  `ai_score` int DEFAULT 0,
  `ai_grade` varchar(2),
  `ai_verdict` enum('strong_buy','buy','watch','pass') DEFAULT 'watch',
  `ai_reason_json` json,
  `ai_risk_json` json,
  `ai_opportunity_json` json,
  `estimated_monthly_sales` int DEFAULT 0,
  `estimated_margin_percent` decimal(5,2) DEFAULT 0,
  `user_decision` enum('pending','track','reject') NOT NULL DEFAULT 'pending',
  `user_memo` text,
  `tracking_id` int,
  `decided_at` timestamp NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `idx_discovery_products_user` (`user_id`, `user_decision`),
  INDEX `idx_discovery_products_job` (`job_id`),
  INDEX `idx_discovery_products_keyword` (`user_id`, `keyword`)
);
